### ISSUE TITLE
[FEAT] 보관함 생성 뷰 구현 

### ISSUE THREAD

**Issue by emjayMJkim** [Team-Growthook/Growthook-AOS#12]
## 📌 TODO

- [ ] 이름, 소개, 공개/비공개 
- [ ] 인사이트 공유 다이얼로그 띄우기
- [ ] 보관함 생성 완료 뷰 구현
