### ISSUE TITLE
[FIX] 2차 QA 반영

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#125]
## 📌 TODO
- [ ] 버전 정보 수정
- [ ] 씨앗 잠금 뷰 stroke 수정
- [ ] 온보딩뷰 이미지 교체 & 이미지 순서 변경
