### ISSUE TITLE
[FEAT] 메인 뷰 UI 완성

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#2]
## 📌 TODO
- [ ] 스크랩 기능 넣기
- [ ] 보관함 클릭시 보관함 상세로 이동
- [ ] 꾸욱 클릭 구현
