### ISSUE TITLE
[FEAT] 홈 뷰 api 구현

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#36]
## 📌 TODO
- [ ] 서버 개발 완료된 api 연결하기
- [ ] api 기초 틀 만들기
- [ ] 홈 뷰 api 연결
- [ ] 보관함 상세 api 연결
