### ISSUE TITLE
[FIX] 기타 에러 수정

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#41]
## 📌 TODO
- [x] 보관함 상세 뷰 삭제 dialog xml 수정
- [x] 뒤로가기 버튼 클릭 시 보관함 상세 조회 api 통신 에러 수정
- [x] 동굴리스트 이미지 바꾸기
- [x] 동굴리스트 bottomSheet 파라미터 수정
