### ISSUE TITLE
[FEAT] 추가로 배포된 씨앗 api 통신 구현

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#49]
## 📌 TODO
- [x] 보관함 별 씨앗 리스트 조회
- [x] 남은 씨앗 알람 조회
- [x] 전체 씨앗 리스트 조회
- [x] 인사이트 잠금 해제
- [x] 씨앗 스크랩 여부 전환
