### ISSUE TITLE
[FEAT] dataStore 셋팅

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#5]
## 📌 TODO
- [ ] dataStore 기초셋팅 
- [ ] 토큰 localDB 저장 구현
- [ ] 닉네임 localDB 저장 구현
- [ ] 자동 로그인 구현
