### ISSUE TITLE
[FEAT] 유저 관련 api 구현

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#52]
## 📌 TODO
- [ ] 회원 탈퇴 
- [ ] 수확한 쑥 개수 조회 
- [ ] 멤버 프로필 조회
- [ ] 사용한 쑥 개수 조회
