### ISSUE TITLE
[FIX] 뷰 및 서버통신 위치 수정

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#53]
## 📌 TODO
- [x] 인사이트 리스트 최하단 가려지는 문제 해결
- [x] 프로필뷰 약관 정책 링크 추가
- [x] 인사이트 클릭시 인사이트 조회로 연결
- [x] 텍스트 길이 TextView width 보다 길면 맨 끝 ... 처리 구현
- [x] observe 함수 분리
- [x] 회원탈퇴 매직넘버 제거
- [x] 마이페이지 api 연결 수정
- [x] 스크랩 목록에서 스크랩 누른 후 로직 수정
- [x] 취소시 스크랩 토스트는 안띄움
- [x] 잠금된 인사이트 꾸욱 기능 제거
