### ISSUE TITLE
[FEAT] 인사이트 조회 api 연결

### ISSUE THREAD

**Issue by amourxyoung** [Team-Growthook/Growthook-AOS#56]
## 📌 TODO
- [ ] 인사이트 이동 api
- [ ] 인사이트 수정 api
- [ ] 인사이트 삭제 api
- [ ] 액션리스트 버튼 ui 수정
