### ISSUE TITLE
[FIX] 뷰 연결 마무리 및 버그 수정

### ISSUE THREAD

**Issue by amourxyoung** [Team-Growthook/Growthook-AOS#66]
## 📌 TODO
- [x] 인사이트 조회 -> 삭제 -> 동굴 상세 보기 연결
- [x] 액션플랜 추가뷰 x 버튼 변경
- [x] 액션 더하기 후 뒤로가기 누르면 홈화면 가게끔
- [x] 완료된 액션플랜 씨앗보기 seedId 수정 
- [x] 액션플랜 쑥 얻기 로직 확인
- [x] 액션플랜 리스트 내에 빈 원소 있는지 검사하는 로직 추가
- [x] 인사이트 조회 메모 엠티 뷰 추가
- [x] 액션플랜&인사이트 스크랩 전환 클릭 로직 수정
