### ISSUE TITLE
[FEAT] Base Dialog 수정

### ISSUE THREAD

**Issue by amourxyoung** [Team-Growthook/Growthook-AOS#75]
## 📌 TODO
- [x] Base Dialog 수정
- [x] 인사이트 잠금 해제 로직 추가
- [x] 남은 쑥 조회 로직 추가
