### ISSUE TITLE
[QA] 미니 큐에이 반영

### ISSUE THREAD

**Issue by amourxyoung** [Team-Growthook/Growthook-AOS#82]
## 📌 TODO
- [x] 리뷰보기 씨앗 invisible 처리

[ 액션플랜 o 인사이트 조회 ] 
- [x] 뒤로 가기 눌렀을 때 홈화면 UI 반영
- [x] 스크랩 클릭 로직 수정
