### ISSUE TITLE
[QA] 최종 QA 반영

### ISSUE THREAD

**Issue by amourxyoung** [Team-Growthook/Growthook-AOS#87]
## 📌 TODO
- [x] 리뷰 작성 여부 상관없이 쑥 얻기 다이얼로그 생성
- [x] 액션플랜x 인사이트 조회 메모 없을 때 empty뷰 삭제
- [X] 액션플랜 완료하면 퍼센티지 반영
