### ISSUE TITLE
[FIX] QA 반영

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS#88]
## 📌 TODO
- [x] 회원 탈퇴시 온보딩 뷰로 이동
- [x] Cave Select 동굴이 없을 경우 "확인"으로 라이팅 수정
- [x] 리뷰 + 액션플랜 bottomSheet 글자 수 제한 확인하기
- [x] myPage padding 확인하기
